<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Terms & Conditions</title>

  <?php include('includes/css.php') ?>
</head>
<body>

  <?php include('reuseables/header.php') ?>
  <?php include('reuseables/sidebar.php') ?>

<div class="container mt-3">
<div class="jumbotron">
    <h3>Terms & Conditions</h3>
    <ol>
        <li>The Site is owned, managed and operated by hockey98.com</li>
        <li>You must be 18 years of age or older to visit or use the Site in any manner. In the event that you are below 18 yrs. of age, you are visiting the Site at your own risk and you alone shall be liable for your actions. By visiting this site or accepting these Terms of Use, you represent and warrant to the Company that you are 18 years of age or older, and that you have the right, authority and capacity to use the Site and agree to and abide by these Terms of Use. You also represent and warrant to the Company that you will use the Site in a manner consistent with any and all applicable laws and regulations.</li>
        <li>By using the Site, you agree to follow and be bound by all terms and conditions concerning your use of the Site. Certain areas of the Site may have different terms of use posted. If there is a conflict between the Terms of Use and terms of use posted for a specific area of the Site, the latter shall have precedence with respect to your use of that area of the Site.
        </li>
        <li>hockey98.com may terminate User’s access to the Site or any part thereof at any time and for any reason without any notice. The provisions regarding disclaimer of warranty, accuracy of information, software, database other system or functionality of website and indemnification shall survive such termination. hockey98.com may monitor User’s access to the Site.
        </li>
        <li>
        hockey98.com may change or discontinue any aspect of the Site at any time, including, its content or features. hockey98.com reserves the right to change the Terms of Use applicable to use of the Site. Such changes shall be effective immediately upon notice, which shall be placed on the Site.</li>
        <li>All contents on the Site are the exclusive property of hockey98.com except the third party content. The software, text, images, graphics, video and audio used on the Site belong to or are licensed to hockey98.com or its subsidiaries and affiliates. No material from the Site may be copied, modified, reproduced, republished, uploaded, transmitted, posted or distributed in any form without prior written permission from hockey98.com . All rights not expressly granted herein are reserved. Unauthorised use of the materials appearing on the Site may violate copyright, trademark and other applicable laws, and could result in criminal or civil penalties. You are granted a non-exclusive, non-transferable, limited right to access the Site and avail the services provided by hockey98.com on the Site.</li>
        <li>hockey98.com does not make any warranties, express or implied, with respect to any service, information, data, software, system, functionality, statements or investment plan made available on the Site. The information contained in the Site has been obtained from sources believed to be reliable. The Site, and all content, materials, information, software and services provided on the Site, are provided on an “as is” and “as available” basis.</li>
        <li>hockey98.com does not warrant that the Site will operate error-free or that the Site and its servers are free of computer viruses or other harmful mechanisms. If your use of the Site or content therein results in the need for servicing or replacing equipment or data, hockey98.com is not responsible for any such costs. Site and investment plan content are provided on an “as is” basis without any warranties of any kind. hockey98.com to the fullest extent permitted by law, disclaims all warranties, whether express or implied, including the fitness for particular purpose and non-infringement. hockey98.com makes no warranties about the accuracy, reliability, completeness, or timeliness of the investment plan of the content, services, software, text, graphics, and links.</li>
        <li>hockey98.com shall not be liable for any damage to User’s Investment, Liability of user investment, commitment given to other users about investment plan and financial return given by user, hockey98.com shall be liable for any unlawful act of the User or its affiliates, relatives, employees, agents including misuse of any data, unfair trade practices, fraud, cybersquatting, hacking and other cybercrimes. In no event shall hockey98.com be liable for damages of any kind, including misuse of this investment plan without limitation, direct, incidental or consequential damages (including, but not limited to, damages for lost profits, business interruption and loss of programs or information) arising out of the use of or inability to use Site, or any information provided thereon, or any claim attributable to errors, omissions or other inaccuracies in the Site.</li>
        <li>You may not send, submit, post, or otherwise transmit, material or messages that contain software virus, or any other files that are designed to interrupt, destroy, and negatively affect in any manner whatsoever, any electronic equipment in connection with the use of the investment business plan Site, or other user’s ability to use the Site.</li>
        <li>User agrees to indemnify and hold hockey98.com , its subsidiaries, affiliates, officers and employees, harmless from any claim, demand or damage, including reasonable attorney’s fees, asserted by any third party due to or arising out of your use of or conduct on the Site hockey98.com reserves the right to disclosure any personal information about you and your use of the Site including its contents, without your prior permission if hockey98.com has a good faith belief that such action is necessary to</li>
        <li>The User’s right to privacy is of paramount importance to hockey98.com . Any information provided by the User will not be shared with any third party, except in the manner provided under these Terms of Use and for the intended purpose for which such information is provided by the User, in which case User’s consent is implied.hockey98.com reserves the right to use the information to provide the User a more personalized online experience.</li>
        <li>If the Site provides links to web sites and access to content, investment plan and services from third parties, including users, advertisers, affiliates and sponsors of the Site, you agree that hockey98.com is not responsible for the availability of, and content provided on, third party web sites or content. The User is requested to peruse the policies posted by other web sites regarding privacy and other topics before use. hockey98.com is not responsible for third party content accessible through the Site, including opinions, advice, statements and advertisements, and User shall bear all risks associated with the use of such content. hockey98.com is not responsible for any loss or damage of any sort which User may incur from dealing with any third party.</li>
        <li>By using any third party content, User may leave the Site and be directed to an external website, or to a website maintained by an entity other than hockey98.com . If you decide to visit any such site, you do so at your own risk and it is your responsibility to take all protective measures to guard against viruses or any other destructive elements.hockey98.com makes no warranty or representation regarding, and does not endorse, any linked web sites or the information appearing thereon or any of the investment plan or services described thereon. Links do not imply that hockey98.com or the Site sponsors, endorses, is affiliated or associated with, or is legally authorized to use any trademark, trade name, logo or copyright symbol displayed in or accessible through the links, or that any linked site is authorized to use any trademark, trade name, logo or copyright symbol of hockey98.com or any of its affiliates or subsidiaries. You hereby expressly acknowledge and agree that the linked sites are not under the control of hockey98.com andhockey98.com is not responsible for the contents of any linked site or any link contained in a linked site, or any changes or updates to such sites. hockey98.com is not responsible for webcasting or any other form of transmission received from any linked site. hockey98.com is providing these links to you only as a convenience, and the inclusion of any link shall not be construed to imply endorsement</li>
        <li>
        For availing the services under the Site, registration by the User is required. You will receive a password and account designation upon completing the registration on the Site. You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all activities that occur under your password or account. By registering, you agree to the following terms in addition to any other specific terms which shall be posted at an appropriate location of the Site. Each registration is for a single individual user only. To access these services, you will be asked to enter your individual User Name and Password. Therefore, we do not permit any of the following:-
        <ol type="a">
            <li>Any other person sharing your User Name and Password.</li>
            <li>Any part of the Site being cached in proxy servers and accessed by individuals who have not registered with Site as users. </li> <li>Access through a single User Name and Password being made available to multiple users on a network.</li>
        </ol>
        </li>
        <li>If we reasonably believe that a User Name and Password are being used / misused in any manner as clarified above, we reserve the right to cancel access rights immediately without notice, and block access to all users from that IP address.
        </li>
        <li>You specifically agree that hockey98.com shall not be responsible for unauthorized access to or alteration of your transmissions or data, any material or data sent or received or not sent or received through the Site.</li>
        <li>Specific Prohibited Uses: This investment business plan database features of the Site may be used only for lawful purposes by individuals seeking investment business information.
            <ol type="a">
                <li>Use Investment plan Database for any purpose other than investment plan , including but not limited to using the information in the investment plan Database to sell or promote any investment plan or services;</li>
                <li>Post or submit to the Site any incomplete, false or inaccurate biographical information or information which is not your own;</li>
                <li>Send unsolicited mail or e-mail, making unsolicited phone calls or send unsolicited faxes regarding promotions and/or advertising of investment plan or services to a user of the Site;</li>
                <li>Delete or revise any material posted by any other person or entity;</li>
                <li>Take any action that imposes an unreasonable or disproportionately large load on the Site’s infrastructure;</li>
                <li>Attempt to decipher, decompile, disassemble or reverse engineer any of the software comprising or in any way making up a part of the Site;</li>
                <li>Aggregate, copy or duplicate in any manner any of the content or information available from the Site; or</li>
                <li>The Users agree not to use / insert any of the User’s URL, web link, e mail address and website while posting any accessing hockey98.com. On non-conformance by users of any of the aforesaid terms may in its sole discretion, restrict or terminate the offending User’s ability to access the Site and determine whether to take any other actions whether to remove or request the removal of the User’s content. hockey98.com shall have no liability or responsibility whatsoever to Users for performance or non-performance of such activities.</li>
            </ol>
        </li>
        <li>
        hockey98.com reserves the right in its sole discretion to investigate and take legal action against anyone who engages in any illegal or prohibited conduct or otherwise violates these Terms of Use, including without limitation, removing the User content from the Site and/or terminating the offending User’s ability to access the Site and/or use services therein.hockey98.com may take any other action with respect to User content or User actions that it deems necessary or appropriate in its sole discretion if it believes it may create liability for hockey98.com or may cause hockey98.com to lose (in whole or in part) the services of its ISPs or other suppliers.</li>
        <li>The User hereby specifically agrees to comply with the requirements of the Subjected Act, as also rules, regulations, guidelines, bye laws and notifications made there under, while on the Site. The user also undertakes that the content provided by him/her is not defamatory, obscene, threatening, abusive or hateful. The User shall alone be responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability there under or under any other law for the time being in force.</li>
        <li>hockey98.com may, if you so choose send direct mailers to you at the address given by you. You have the option to ‘opt-out’ of this direct mailer by way of links provided at the bottom of each mailer. hockey98.com respects your privacy and in the event that you choose to not receive such mailers, hockey98.com will take all steps to remove you from the list.</li>
        <li>hockey98.com recognizes the receipt, transmission or distribution of spam emails (unsolicited bulk emails) as a major concern and has taken reasonable measures to minimize the transmission and effect of spam emails in its computing environment. All emails received by hockey98.com, are subject to spam check. Any email identified as spam will be rejected with sufficient information to the Sender for taking necessary action. With this measure, along with other technical spam reduction measures, hockey98.com hopes to minimize the effect of spam emails. hockey98.com reserves the right to reject and/or report any suspicious spam emails, to the authorities concerned, for necessary action, from time to time.</li>
        <li>
          You will be provided with 98 Rs. Account. This account will contain videos of hockey game which is our national game. This is not a company. 98 Rs. that you will be charged is used to give you hockey videos. We don't force anyone to come to this website. You can come to this website at your own risk. You can see hockey videos by your wish by paying 98 Rs.
        </li>
        <li>No failure or delay by hockey98.com in exercising any right, power or privilege under the Terms of Use will operate as a waiver of it, nor will any single or partial exercise of it preclude any further exercise or the exercise of any right, power or privilege under the Terms of Use.</li>
        <li>The Site is controlled, operated and administered by hockey98.com from its offices within India. hockey98.com makes no representation that Materials on this site are appropriate or available for use at any other location(s) outside India. Any access to this site from territories where their contents are illegal is prohibited. You may not use the site or export the materials in violation of any applicable export laws and regulations. If you access this site from a location outside India, you are responsible for compliance with all local laws.</li>
        <li>You just shall inform to hockey98.com about any informality due diligence, negligence, and investment and return issues to hockey98.com. hockey98.com will be availed 30 to 60 days period for request generated by users. User should not inform, convey or post to any social media, email campaigning or any other destructing activities about hockey98.com before resolve if such happens hockey98.com will take stringent lawful action against to user and user may need to pay for defamatory charges.</li>
        <li>The Terms of Use shall be governed by the Laws of India. The Courts of law at Maharashtra State shall have exclusive jurisdiction over any disputes arising under the Terms of Use.</li>
    </ol>
</div>
</div>
  <?php include('includes/js.php') ?>

</body>
</html>
